#!/bin/sh
# Pushes files generated by Asciidoctor and associated files to gh-pages branch for commits to master branch.

set -o errexit # exit with nonzero exit code if any line fails
set -o nounset # exit if variable is unset

# Pull requests and commits to other branches should not try to deploy.
if [ "false" != "$TRAVIS_PULL_REQUEST" -o "master" != "$TRAVIS_BRANCH" ]; then
  echo "Not a commit to master branch. Skipping deploy to GitHub Pages."
  exit 0
fi

cd build/docs/html5

git init
git config user.name "Travis"
git config user.email "travis@travis-ci.org"

git remote add upstream "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"

# In commands below, 2>/dev/null discards output to avoid leaking $GITHUB_TOKEN to Travis logs e.g. if error occurs

# Reset to gh-pages branch, or create orphan branch if gh-pages does not exist in remote.
if git ls-remote --exit-code --heads upstream gh-pages 2>/dev/null; then
    git fetch --depth=1 upstream gh-pages 2>/dev/null
    git reset upstream/gh-pages 2>/dev/null
elif [ $? -eq 2 ]; then # exit code of git ls-remote is 2 if branch does not exist
    git checkout --orphan gh-pages 2>/dev/null
else # error occurred
    exit $?
fi

# Exit if there are no changes to gh-pages files.
if changes=$(git status --porcelain) && [ -z "$changes" ]; then
    echo "No changes to GitHub Pages files; exiting."
    exit 0
fi

git add -A .
git commit -m "Rebuild pages at ${TRAVIS_COMMIT}"
git push --quiet upstream HEAD:gh-pages 2>/dev/null
