language: java
matrix:
  include:
    - jdk: oraclejdk8

script: >-
    ./config/travis/run-checks.sh &&
    travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls -i

before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"

after_success:
  - bash push.sh

addons:
  apt:
    packages:
      - oracle-java8-installer
