language: java
matrix:
  include:
    - jdk: oraclejdk8

script: >-
    ./config/travis/run-checks.sh &&
    travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor &&
    exec config/travis/deploy_github_pages.sh 2>/dev/null

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer
