#!/usr/bin/env bash
#
# Pushes files generated by Asciidoctor and associated files to gh-pages branch for commits to master branch.

set -o errexit # exit with nonzero exit code if any line fails
set -o nounset # exit if variable is unset

if [[ "true" = "$TRAVIS_PULL_REQUEST" || "master" != "$TRAVIS_BRANCH" ]]; then
  echo "Not a commit to master branch. Skipping deploy to GitHub Pages." >&2
  exit 0
fi

GITHUB_REPO="se-edu/addressbook-level4.git"
commit_sha=$(git rev-parse --short HEAD)

cd build/docs/html5

git init
git config user.name "Travis"
git config user.email "travis@travis-ci.org"

git remote add upstream "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}"

# >/dev/null 2>&1 discards output to avoid leaking $GITHUB_TOKEN to Travis logs e.g. if error occurs
git fetch upstream >/dev/null 2>&1

# Create gh-pages branch if it doesn't exist
git reset upstream/gh-pages || git checkout --orphan gh-pages

git add -A .
git commit -m "Rebuild pages at ${commit_sha}"
git push -q upstream HEAD:gh-pages >/dev/null 2>&1
