= Using AsciiDoc and Asciidoctor

link:asciidoctor.org[AsciiDoc] is a lightweight markup language that can be translated into various formats such as HTML, DocBook and PDF, using text processor and publishing toolchain  <<UsingGradle.adoc#rendering-asciidoc-files, Asciidoctor>>.

== Writing AsciiDoc

You can write AsciiDoc documents by using any text editor, then saving the file with the file extension `.adoc`.

For a quick guide to the syntax, see link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference[this].

[NOTE]
AsciiDoctor uses slightly different syntax from AsciiDoc, to support faster processing, offer additional features, and decrease ambiguity. Hence, you should follow Asciidoctor's syntax when writing AsciiDoc documents.

== Previewing

To preview AsciiDoc documents locally, you can use <<UsingGradle.adoc#rendering-asciidoc-files, Asciidoctor>> to render the files to HTML.
You can also install link:http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/[tools] that support live preview.

== Customizing

=== Using stylesheets

To style the HTML documents generated from AsciiDoc files, edit `gh-pages.css` in the `docs\stylesheets` folder.
`gh-pages.css` imports `asciidoctor.css`, which is the default stylesheet by Asciidoctor.

=== Custom blocks

You can create your own custom blocks, like the `details` block in link:UserGuide.adoc[].
For more examples, see link:http://asciidoctor.org/docs/user-manual/#block-assignment-2[Asciidoctor's guide] and link:https://leanpub.com/awesomeasciidoctornotebook/read#leanpub-auto-apply-custom-styling-to-blocks[this tutorial].

=== Custom macros

Custom macros, like the `cmd` inline macro used in link:UserGuide.adoc[], can be added to `asciidoctor` extensions in `build.gradle`.
link:https://mrhaki.blogspot.sg/2015/03/awesome-asciidoctor-use-inline.html[Here] is another example.

=== Custom extensions

More complicated macros and extensions can be added in other ways, such as link:http://asciidoctor.org/docs/asciidoctor-gradle-plugin/#adding-custom-extensions[using Gradle] (link:https://uberconf.com/blog/andres_almiray/2014/08/gradle_glam_custom_asciidoctor_extensions[an example]), or link:https://github.com/asciidoctor/asciidoctor-extensions-lab[Asciidoctor's Ruby based extensions lab].

== Troubleshooting

*Problem: Asciidoc is not displayed properly in GitHub preview even though it is rendered correctly in HTML*

* Reason: GitHub preview renders certain elements differently from AsciiDoc's defaults (e.g. section links). Furthermore, GitHub preview only supports basic features of AsciiDoc.
* Solution: Change AsciiDoc's settings to match GitHub preview's defaults if possible.
  You can also choose to display different things when in GitHub preview, as described link:http://asciidoctor.org/news/2014/02/04/github-asciidoctor-0.1.4-upgrade-5-things-to-know/#long-live-asciidoc-on-github[here].
// TODO: replace changing defaults with "Make sure you have followed the coding standard for AsciiDoc." when coding standard is completed

*Problem: Asciidoctor is ignoring the attributes set in the document header.*

* Reason: Header attributes are overridden by attributes specified in `asciidoctor` in `build.gradle`.
* Solution: Remove the attribute from `build.gradle` and set the attribute in individual document headers instead.

== Resources

* Check out link:https://github.com/darshandsoni/asciidoctor-skins[asciidoctor-skins] repository for custom stylesheets.
* For miscellaneous useful tutorials, see link:https://leanpub.com/awesomeasciidoctornotebook/read[Awesome Asciidoctor Notebook]
